### ISSUE TITLE
[Bug; Crash] Subscription group with Patreon creator crashes application

### ISSUE THREAD

**Issue by VoxelPrismatic** [futo-org/grayjay-android#1058]
## Summary
Creating a subscription group with a Patreon creator will crash the application when trying to load the group's feed.

## Steps to Reproduce
1. Subscribe to anyone on Patreon
   - If you need to add one, I recommend the following:
       - [CoffeeZilla][coffee] @ $5/mo;
       - [Beside the Dying Fire][BtDF] @ $1/mo;
       - [Technology Connections][tech] @ $1/mo;
2. Add creator to subscription group
3. Load subscription group
4. Scroll until crash

[coffee]: https://www.patreon.com/Coffeezilla?utm_campaign=creatorshare_fan
[BtDF]: https://www.patreon.com/besidethedyingfire?utm_campaign=creatorshare_fan
[tech]: https://www.patreon.com/technologyconnections?utm_campaign=creatorshare_fan

## Video of reproduction

https://github.com/futo-org/grayjay-android/assets/45671764/ecaa7dbf-d954-4601-908f-dff83e268ee9

## Version details
- Android 14
- Samsung S22; OneUI 6.1
- Grayjay v242 release
  - Patreon v15
  - Rumble v33
  - YouTube v177
  - Nebula v9
  - Twitch v14

## Suspicions
Since Patreon links to other sources, I suspect that the `R.id.loader` is set to null. I cannot confirm since I cannot locate `com/futo/platformplayer/R.kt` 

## Traceback
```java
Version information (version_name = 242, version_code = 242, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = r0q, version-sdk = 34, version-os = samsung/r0qsqw/r0q:14/UP1A.231005.007/S901USQU4EXE1:user/release-keys)

(e, ExceptionActivity, 2024-06-05 04:15:05): Uncaught exception ("Unknown Context"): findViewById(...) must not be null

java.lang.NullPointerException: findViewById(...) must not be null
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewNestedVideoView.<init>(PreviewNestedVideoView.kt:46)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewNestedVideoViewHolder.<init>(PreviewNestedVideoViewHolder.kt:28)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewContentListAdapter.createNestedViewHolder(PreviewContentListAdapter.kt:93)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewContentListAdapter.createChild(PreviewContentListAdapter.kt:83)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewContentListAdapter.createChild(PreviewContentListAdapter.kt:27)
	at com.futo.platformplayer.views.adapters.InsertedViewAdapter.onCreateViewHolder(InsertedViewAdapter.kt:38)
	at com.futo.platformplayer.views.adapters.InsertedViewAdapter.onCreateViewHolder(InsertedViewAdapter.kt:8)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7788)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6873)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4022)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:705)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:100)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2381)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:452)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:750)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:551)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:486)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solvingPass(Direct.java:224)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:693)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:2936)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7390)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1036)
	at android.view.View.measure(View.java:28571)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:5203)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3603)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3973)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
	at android.view.Choreographer.doFrame(Choreographer.java:1079)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8919)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by grayjay-support-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
