### ISSUE TITLE
Crash when importing or subscribing to SoundCloud channel

### ISSUE THREAD

**Issue by gsture** [futo-org/grayjay-android#1127]
### What happened?

When subscribing to a SoundCloud channel or importing a newpipe list with SoundCloud channels the app imidiatelly crashes. 

### Grayjay Version

249

### What plugins are you seeing the problem on?

SoundCloud

### Plugin Version

13

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Version information (version_name = 249, version_code = 249, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = shiba, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-07-10 15:46:49): Uncaught exception ("Unknown Context"): Parameter specified as non-null is null: method kotlinx.serialization.internal.StringSerializer.serialize, parameter value

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.internal.StringSerializer.serialize, parameter value
	at kotlinx.serialization.internal.StringSerializer.serialize(Unknown Source:7)
	at kotlinx.serialization.internal.StringSerializer.serialize(Primitives.kt:156)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:226)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:123)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:226)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at com.futo.platformplayer.api.media.models.channels.SerializedChannel.write$Self(SerializedChannel.kt:12)
	at com.futo.platformplayer.api.media.models.channels.SerializedChannel$$serializer.serialize(SerializedChannel.kt:12)
	at com.futo.platformplayer.api.media.models.channels.SerializedChannel$$serializer.serialize(SerializedChannel.kt:12)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:226)
	at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
	at com.futo.platformplayer.models.Subscription.write$Self(Subscription.kt:14)
	at com.futo.platformplayer.models.Subscription$$serializer.serialize(Subscription.kt:14)
	at com.futo.platformplayer.models.Subscription$$serializer.serialize(Subscription.kt:14)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:226)
	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:31)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:81)
	at com.futo.platformplayer.stores.v2.JsonStoreSerializer.serialize(ManagedStore.kt:485)
	at com.futo.platformplayer.stores.v2.ManagedStore.saveNew(ManagedStore.kt:310)
	at com.futo.platformplayer.stores.v2.ManagedStore.save(ManagedStore.kt:265)
	at com.futo.platformplayer.stores.v2.ManagedStore.save$default(ManagedStore.kt:250)
	at com.futo.platformplayer.states.StateSubscriptions.addSubscription(StateSubscriptions.kt:228)
	at com.futo.platformplayer.views.subscriptions.SubscribeButton.handleSubscribe(SubscribeButton.kt:75)
	at com.futo.platformplayer.views.subscriptions.SubscribeButton._init_$lambda$0(SubscribeButton.kt:62)
	at com.futo.platformplayer.views.subscriptions.SubscribeButton.$r8$lambda$8rX5XCFgo-FHyN1a-kyPxoyW2kU(Unknown Source:0)
	at com.futo.platformplayer.views.subscriptions.SubscribeButton$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7931)
	at android.view.View.performClickInternal(View.java:7908)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30990)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by Zvonimir-FUTO** [comment]
This was fixed in version 14.
