### ISSUE TITLE
App crashing on startup - WorkManager is not initialized properly

### ISSUE THREAD

**Issue by DMarwan** [futo-org/grayjay-android#1150]
### What happened?

Hello.

I have a bug I'd like to report and get some help with.
When opening the app, I get the following screen:

![Screenshot_2024-07-14-14-43-46-368](https://github.com/user-attachments/assets/535395ea-6a64-48f5-8dc7-95002380e240)

It didn't happen until today, and I haven't updated the app or took any action that could break the app whatsoever.
The suggested options to submit and check for updates fail, and the restart one doesn't seem to work either. 

I tried reinstalling the APK, to no avail.

I usually use YouTube and bilibili plugins, not sure if that is related in anyway.

Any clues as how to solve this? 
Thanks in advance for your help.

### Grayjay Version

249

### What plugins are you seeing the problem on?

All, Youtube, BiliBili (CN)

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

### Relevant log output

```shell
Version information (version_name = 249, version_code = 249, flavor = stable, build_type = release)
Device information (brand= nubia, manufacturer = nubia, device = NX669J-EEA, version-sdk = 32, version-os = )

(e, ExceptionActivity, 2024-07-14 12:42:11): Uncaught exception ("Unknown Context"): WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.

java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:170)
	at androidx.work.WorkManager.getInstance(WorkManager.java:184)
	at com.futo.platformplayer.states.StateApp.scheduleBackgroundWork(StateApp.kt:617)
	at com.futo.platformplayer.states.StateApp.mainAppStarted(StateApp.kt:512)
	at com.futo.platformplayer.activities.MainActivity.onCreate(MainActivity.kt:421)
	at android.app.Activity.performCreate(Activity.java:8250)
	at android.app.Activity.performCreate(Activity.java:8230)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1367)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4082)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4267)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2454)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:242)
	at android.os.Looper.loop(Looper.java:374)
	at android.app.ActivityThread.main(ActivityThread.java:9333)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:614)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1018)
```

**Comment by DMarwan** [comment]
Update: I randomly tried to open the app just now and it seems to work. Didn't do anything, not even restart my phone. I don't know if I should close the issue or if it's worth keeping it for further review. 

If this happens again I shall re-open another issue or comment an update here.
