### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by koen-futo** [futo-org/grayjay-android#123]
Version information (version_name = 181, version_code = 181, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = panther, version-sdk = 33, version-os = )

(e, ExceptionActivity, 2023-10-29 15:23:12): Uncaught exception ("Unknown Context"): Receiver not registered: com.futo.platformplayer.receivers.AudioNoisyReceiver@400365

java.lang.IllegalArgumentException: Receiver not registered: com.futo.platformplayer.receivers.AudioNoisyReceiver@400365
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1662)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1836)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:812)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:812)
	at com.futo.platformplayer.states.StateApp.mainAppStarted(StateApp.kt:426)
	at com.futo.platformplayer.activities.MainActivity.onCreate(MainActivity.kt:361)
	at android.app.Activity.performCreate(Activity.java:8342)
	at android.app.Activity.performCreate(Activity.java:8321)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1417)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3625)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:138)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2306)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7918)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)

**Comment by Zvonimir-FUTO** [comment]
Closing.
