### ISSUE TITLE
Another crash on startup.

### ISSUE THREAD

**Issue by Keetarin** [futo-org/grayjay-android#1230]
### What happened?

As it's starting up, either before the home screen loads or just as it loads, it crashes. 

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Version information (version_name = 253, version_code = 253, flavor = stable, build_type = release)
Device information (brand= Teracube, manufacturer = Teracube, device = emerald, version-sdk = 32, version-os = )

(e, ExceptionActivity, 2024-08-07 03:00:33): Uncaught exception ("Unknown Context"): Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{dd3d0dc u0 com.futo.platformplayer/.services.DownloadService}

android.app.RemoteServiceException$ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{dd3d0dc u0 com.futo.platformplayer/.services.DownloadService}
	at android.app.ActivityThread.generateForegroundServiceDidNotStartInTimeException(ActivityThread.java:1965)
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:1936)
	at android.app.ActivityThread.access$2700(ActivityThread.java:256)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2190)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7870)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by Keetarin** [comment]
One of the recurring problems that caused this was that the app periodically opens as if I closed it, this happened during a large download. I don't know whether the download broke the app or the app broke the download, but whichever is the case the app is broken now and won't fully load.

**Comment by support-grayjay** [comment]
This should be fixed in the latest version of Grayjay (v264). If you are still encountering the issue, feel free to reopen it.
