### ISSUE TITLE
Issues when subscribing to Soundcloud channels

### ISSUE THREAD

**Issue by Auster-1** [futo-org/grayjay-android#1240]
### What happened?

When trying to subscribe to a channel through the player, no response happens. When trying to subscribe through the creator's page, Grayjay crashes.

### Grayjay Version

253

### What plugins are you seeing the problem on?

SoundCloud

### Plugin Version

13

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
Version information (version_name = 253, version_code = 253, flavor = stable, build_type = release)
Device information (brand= Xiaomi, manufacturer = Xiaomi, device = sweet, version-sdk = 33, version-os = )

(e, ExceptionActivity, 2024-08-11 12:03:30): Uncaught exception ("Unknown Context"): Parameter specified as non-null is null: method kotlinx.serialization.internal.StringSerializer.serialize, parameter value

java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.internal.StringSerializer.serialize, parameter value
 at kotlinx.serialization.internal.StringSerializer.serialize(Unknown Source:7)
 at kotlinx.serialization.internal.StringSerializer.serialize(Primitives.kt:156)
 at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:226)
 at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
 at kotlinx.serialization.internal.MapLikeSerializer.serialize(CollectionSerializers.kt:123)
 at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:226)
 at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
 at com.futo.platformplayer.api.media.models.channels.SerializedChannel.write$Self(SerializedChannel.kt:12)
 at com.futo.platformplayer.api.media.models.channels.SerializedChannel$$serializer.serialize(SerializedChannel.kt:12)
 at com.futo.platformplayer.api.media.models.channels.SerializedChannel$$serializer.serialize(SerializedChannel.kt:12)
 at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:226)
 at kotlinx.serialization.encoding.AbstractEncoder.encodeSerializableElement(AbstractEncoder.kt:80)
 at com.futo.platformplayer.models.Subscription.write$Self(Subscription.kt:14)
 at com.futo.platformplayer.models.Subscription$$serializer.serialize(Subscription.kt:14)
 at com.futo.platformplayer.models.Subscription$$serializer.serialize(Subscription.kt:14)
 at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:226)
 at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:31)
 at kotlinx.serialization.json.Json.encodeToString(Json.kt:81)
 at com.futo.platformplayer.stores.v2.JsonStoreSerializer.serialize(ManagedStore.kt:485)
 at com.futo.platformplayer.stores.v2.ManagedStore.saveNew(ManagedStore.kt:310)
 at com.futo.platformplayer.stores.v2.ManagedStore.save(ManagedStore.kt:265)
 at com.futo.platformplayer.stores.v2.ManagedStore.save$default(ManagedStore.kt:250)
 at com.futo.platformplayer.states.StateSubscriptions.addSubscription(StateSubscriptions.kt:228)
 at com.futo.platformplayer.views.subscriptions.SubscribeButton.handleSubscribe(SubscribeButton.kt:75)
 at com.futo.platformplayer.views.subscriptions.SubscribeButton._init_$lambda$0(SubscribeButton.kt:62)
 at com.futo.platformplayer.views.subscriptions.SubscribeButton.$r8$lambda$8rX5XCFgo-FHyN1a-kyPxoyW2kU(Unknown Source:0)
 at com.futo.platformplayer.views.subscriptions.SubscribeButton$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
 at android.view.View.performClick(View.java:7506)
 at android.view.View.performClickInternal(View.java:7483)
 at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
 at android.view.View$PerformClick.run(View.java:29357)
 at android.os.Handler.handleCallback(Handler.java:942)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:201)
 at android.os.Looper.loop(Looper.java:288)
 at android.app.ActivityThread.main(ActivityThread.java:7893)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

**Comment by Auster-1** [comment]
Small update:
Grayjay appears to be able to subscribe to some channels, but not others. For example, the channel Phyrnna (link ID "phyrnna") behaves in the faulty way described in the OP, while Nightwish (link ID "nightwish") could be subscribed to without incidents.

**Comment by Nutzer** [comment]
I just encountered the exact same issue.
The problem is that the Soundcloud plugin tries to parse the header thumbnail of a channel as an external link (because the API treats them the same), which then trips up the serializer. The channels that do work don't have a header thumbnail set.

I put the fix below, but I don't have access to FUTO's gitlab instance, so I can't add an issue/pr there myself.

```diff --git a/SoundcloudScript.js b/SoundcloudScript.js
index 0198088..68eef72 100644
--- a/SoundcloudScript.js
+++ b/SoundcloudScript.js
@@ -585,7 +585,7 @@ function soundcloudUserToPlatformChannel(scu) {
         subscribers: scu.followers_count,
         description: scu.description,
         url: scu.permalink_url,
-        links: scu.visuals ? scu.visuals.visuals.map((v) => v.link) : [],
+        links: scu.visuals ? scu.visuals.visuals.filter((v) => v.link).map((v) => v.link) : [],
     })
 }
```
