### ISSUE TITLE
App crashed permanently 

### ISSUE THREAD

**Issue by ScheldonFernandes** [futo-org/grayjay-android#1257]
### What happened?

![Screenshot_20240821_185801_Grayjay](https://github.com/user-attachments/assets/4c2d6adb-160b-43c6-bfac-f810f1b1959a)
This morning the app stop working and only show this error mensage, I clean the cache, update, uninstall and reinstall the app, and the problem persist

### Grayjay Version

253

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Version information (version_name = 253, version_code = 253, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = gta7lite, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-08-21 23:03:24): Uncaught exception ("Contexto desconhecido"): WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.

java.lang.IllegalStateException: WorkManager is not initialized properly.  You have explicitly disabled WorkManagerInitializer in your manifest, have not manually called WorkManager#initialize at this point, and your Application does not implement Configuration.Provider.
	at androidx.work.impl.WorkManagerImpl.getInstance(WorkManagerImpl.java:170)
	at androidx.work.WorkManager.getInstance(WorkManager.java:184)
	at com.futo.platformplayer.states.StateApp.scheduleBackgroundWork(StateApp.kt:630)
	at com.futo.platformplayer.states.StateApp.mainAppStarted(StateApp.kt:525)
	at com.futo.platformplayer.activities.MainActivity.onCreate(MainActivity.kt:470)
	at android.app.Activity.performCreate(Activity.java:8960)
	at android.app.Activity.performCreate(Activity.java:8929)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:230)
	at android.os.Looper.loop(Looper.java:319)
	at android.app.ActivityThread.main(ActivityThread.java:8913)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

**Comment by TrippyHippyDan** [comment]
I am also having this issue. I have yet to do an uninstall and reinstall. That is my next step.

```
Version information (version_name = 253, version_code = 253, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = akita, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-09-02 15:35:21): Uncaught exception ("Unknown Context"): Attempted to add 2 clients with the same ID

java.lang.IllegalStateException: Attempted to add 2 clients with the same ID
	at com.futo.platformplayer.states.StatePlatform$updateAvailableClients$2.invokeSuspend(StatePlatform.kt:212)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```
Uninstalling, rebooting, and reinstalling was the only thing that allowed me to fix this.

**Comment by usertoroot** [comment]
Looking at this issue now.

**Comment by usertoroot** [comment]
Proposed fix is out (WorkManager).

Anybody with this issue able to give me some details on which device/android version?

**Comment by Kelvin-FUTO** [comment]
> I am also having this issue. I have yet to do an uninstall and reinstall. That is my next step.
> 
> ```
> Version information (version_name = 253, version_code = 253, flavor = stable, build_type = release)
> Device information (brand= google, manufacturer = Google, device = akita, version-sdk = 34, version-os = )
> 
> (e, ExceptionActivity, 2024-09-02 15:35:21): Uncaught exception ("Unknown Context"): Attempted to add 2 clients with the same ID
> 
> java.lang.IllegalStateException: Attempted to add 2 clients with the same ID
> 	at com.futo.platformplayer.states.StatePlatform$updateAvailableClients$2.invokeSuspend(StatePlatform.kt:212)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
> 	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
> ```
> 
> Uninstalling, rebooting, and reinstalling was the only thing that allowed me to fix this.

In next Grayjay version I made it so it no longer crashes. Technically the scenario should be impossible to reach, but atleast nof if you do, it will show a dialog telling you the offending plugins, and allow you to atleast uninstall one.

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
