### ISSUE TITLE
Subscriptions tab error after importing data from kick

### ISSUE THREAD

**Issue by ardaevin0** [futo-org/grayjay-android#127]
Version information (version_name = 181, version_code = 181, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = a51, version-sdk = 33, version-os = )

(e, ExceptionActivity, 2023-10-30 10:00:13): Uncaught exception ("Unknown Context"): List is empty.

java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:214)
	at com.futo.platformplayer.api.media.structures.DedupContentPager.dedupResults(DedupContentPager.kt:55)
	at com.futo.platformplayer.api.media.structures.DedupContentPager.<init>(DedupContentPager.kt:25)
	at com.futo.platformplayer.cache.ChannelContentCache.getSubscriptionCachePager(ChannelContentCache.kt:58)
	at com.futo.platformplayer.fragment.mainactivity.main.SubscriptionsFeedFragment$SubscriptionsFeedView.loadResults(SubscriptionsFeedFragment.kt:283)
	at com.futo.platformplayer.fragment.mainactivity.main.SubscriptionsFeedFragment$SubscriptionsFeedView.loadResults$default(SubscriptionsFeedFragment.kt:279)
	at com.futo.platformplayer.fragment.mainactivity.main.SubscriptionsFeedFragment$SubscriptionsFeedView.onShown(SubscriptionsFeedFragment.kt:119)
	at com.futo.platformplayer.fragment.mainactivity.main.SubscriptionsFeedFragment.onShownWithView(SubscriptionsFeedFragment.kt:54)
	at com.futo.platformplayer.fragment.mainactivity.main.MainFragment.onShown(MainFragment.kt:41)
	at com.futo.platformplayer.activities.MainActivity.navigate(MainActivity.kt:821)
	at com.futo.platformplayer.activities.MainActivity.navigate$default(MainActivity.kt:749)
	at com.futo.platformplayer.fragment.mainactivity.MainActivityFragment.navigate(MainActivityFragment.kt:26)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$Companion$buttonDefinitions$4.invoke(MenuBottomBarFragment.kt:380)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$Companion$buttonDefinitions$4.invoke(MenuBottomBarFragment.kt:346)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.updateBottomMenuButtons$lambda$5(MenuBottomBarFragment.kt:192)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.$r8$lambda$xHjIl7xd49czzDh2bTnrIEFGjp8(Unknown Source:0)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView$$ExternalSyntheticLambda0.onClick(Unknown Source:4)
	at android.view.View.performClick(View.java:7881)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView$MenuButton._init_$lambda$0(MenuBottomBarFragment.kt:330)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView$MenuButton.$r8$lambda$Kmm6hqFV7eZc9dW2xpwBGXk52vU(Unknown Source:0)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView$MenuButton$$ExternalSyntheticLambda0.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:7881)
	at android.view.View.performClickInternal(View.java:7858)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30863)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by Kelvin-FUTO** [comment]
I believe this was fixed this week or last week. If not re-open.
