### ISSUE TITLE
Illegal use of wildcards on second level domain(cant log ino youtube plugin)

### ISSUE THREAD

**Issue by ifezcool** [futo-org/grayjay-android#1295]
### What happened?

getting this error trying to relog into youtube plugin:

(e, ExceptionActivity, 2024-09-05 09:45:58): Uncaught exception ("Unknown Context"): Illegal use of wildcards on Second-Level-Domain

java.lang.IllegalStateException: Illegal use of wildcards on Second-Level-Domain
    at com.futo.platformplayer.Extensions_FormattingKt.matchesDomain(Extensions_Formatting.kt:367)
    at com.futo.platformplayer.others.LoginWebViewClient.shouldInterceptRequest(LoginWebViewClient.kt:114)
    at WV.v6.a(chromium-TrichromeWebViewGoogle.aab-stable-661308830:83)
    at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-TrichromeWebViewGoogle.aab-stable-661308830:15)

### Grayjay Version

259

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

196

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Relevant log output

```shell
(e, ExceptionActivity, 2024-09-05 09:45:58): Uncaught exception ("Unknown Context"): Illegal use of wildcards on Second-Level-Domain

java.lang.IllegalStateException: Illegal use of wildcards on Second-Level-Domain
    at com.futo.platformplayer.Extensions_FormattingKt.matchesDomain(Extensions_Formatting.kt:367)
    at com.futo.platformplayer.others.LoginWebViewClient.shouldInterceptRequest(LoginWebViewClient.kt:114)
    at WV.v6.a(chromium-TrichromeWebViewGoogle.aab-stable-661308830:83)
    at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-TrichromeWebViewGoogle.aab-stable-661308830:15)
```

**Comment by Justin-ojay** [comment]
Having the same problem as him

**Comment by usertoroot** [comment]
Will look into it

**Comment by gabrielbecker** [comment]
Same problem here.

**Comment by Kelvin-FUTO** [comment]
Are you using the official Youtube plugin? 
Because the official one doesn't use any wildcards, so thats a bit confusing.

**Comment by Kelvin-FUTO** [comment]
Nvm, think I might have found the cause.

**Comment by ifezcool** [comment]
> Nvm, think I might have found the cause.

i see, do you happen to have a solution?

**Comment by Kelvin-FUTO** [comment]
Yup, A fix will be included in next hotfix (tomorrow most likely)

**Comment by ifezcool** [comment]
> Yup, A fix will be included in next hotfix (tomorrow most likely)

thank you, appreciated

**Comment by Justin-ojay** [comment]
Nice

**Comment by Kelvin-FUTO** [comment]
Fix should be deployed (v261)
