### ISSUE TITLE
Logging in to Youtube crashes GrayJay

### ISSUE THREAD

**Issue by dreetie** [futo-org/grayjay-android#1297]
### What happened?

When I go to the settings of the Youtube plugin -> login -> log in to my google account -> and select my channel the app crashes with message:
Empty error

Javax.crypto.IllegalBlockSizeException at ....  

### Grayjay Version

259

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

200

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

### Relevant log output

```shell
Version information (version_name = 259, version_code = 259, flavor = stable, build_type = release)
Device information (brand= motorola, manufacturer = motorola, device = lisbon, version-sdk = 31, version-os = motorola/lisbon_retaile/lisbon:12/S3RL32.114-25/7d128e:user/release-keys)

(e, ExceptionActivity, 2024-09-06 15:10:10): Uncaught exception ("Unknown Context"): Empty error

javax.crypto.IllegalBlockSizeException
 at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:613)
 at javax.crypto.Cipher.doFinal(Cipher.java:2056)
 at com.futo.platformplayer.encryption.GEncryptionProviderV1.encrypt(GEncryptionProviderV1.kt:42)
 at com.futo.platformplayer.encryption.GEncryptionProviderV1.encrypt(GEncryptionProviderV1.kt:34)
 at com.futo.platformplayer.api.media.platforms.js.SourceEncrypted$Companion.fromDecrypted(SourceEncrypted.kt:23)
 at com.futo.platformplayer.api.media.platforms.js.SourceAuth.toEncrypted(SourceAuth.kt:14)
 at com.futo.platformplayer.api.media.platforms.js.SourcePluginDescriptor.updateAuth(SourcePluginDescriptor.kt:75)
 at com.futo.platformplayer.states.StatePlugins.setPluginAuth(StatePlugins.kt:583)
 at com.futo.platformplayer.fragment.mainactivity.main.SourceDetailFragment$SourceDetailView$loginSource$2$1.invoke(SourceDetailFragment.kt:400)
 at com.futo.platformplayer.fragment.mainactivity.main.SourceDetailFragment$SourceDetailView$loginSource$2$1.invoke(SourceDetailFragment.kt:399)
 at com.futo.platformplayer.activities.LoginActivity$onCreate$2.invoke(LoginActivity.kt:72)
 at com.futo.platformplayer.activities.LoginActivity$onCreate$2.invoke(LoginActivity.kt:69)
 at com.futo.platformplayer.constructs.Event1.emit(Event.kt:99)
 at com.futo.platformplayer.others.LoginWebViewClient.shouldInterceptRequest(LoginWebViewClient.kt:191)
 at WV.v6.a(chromium-TrichromeWebViewGoogle6432.aab-stable-661312733:83)
 at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-TrichromeWebViewGoogle6432.aab-stable-661312733:15)
Caused by: android.security.KeyStoreException: Memory allocation failed
 at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:356)
 at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
 at android.security.KeyStoreOperation.update(KeyStoreOperation.java:114)
 at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.update(KeyStoreCryptoOperationChunkedStreamer.java:222)
 at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.update(KeyStoreCryptoOperationChunkedStreamer.java:156)
 at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:179)
 at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:603)
 ... 15 more
```

**Comment by mattvisa** [comment]
Same issue. Seems to be related to captcha verification on my end.

**Comment by Stormhammer1399** [comment]
I've been having this issue with the captcha to detect bots as well. Sometimes I get a few hours without it failing; other times I get through a video and a half and it fails.

**Comment by usertoroot** [comment]
Will look on Monday. Can you guys please let me know which Android OS, device, etc you are using? It doesn't seem like all devices are affected.

**Comment by dreetie** [comment]
Device: Motorola G60s (XT2133-2)
Android version: 12 with android security update of 01/08/2023
kernel version: 4.14.186+

**Comment by Stormhammer1399** [comment]
Device: Google Pixel 6
Android version: 14 with security patch 06/05/2024
Kernel: 5.10.198+

**Comment by support-grayjay** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
