### ISSUE TITLE
Login required/videos wont load at all when vpn is on

### ISSUE THREAD

**Issue by SunnySapphire** [futo-org/grayjay-android#1334]
### What happened?

"block detected, attempting bypass" and then the whole video restarts from the beginning everytime i try to watch any videos with a vpn on and after trying to fast forward back to where  i was which caused me to be blocked a few more times which then led to the whole app crashing and giving an error log saying "sign in to confirm you are not a bot" this error has been happening since a few versions ago of the plugin and greyjay, 

### Grayjay Version

264

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

204

### When do you experience the issue?

- [ ] While logged in
- [X] While logged out
- [ ] N/A

### Relevent error code
Version information (version_name = 264, version_code = 264, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = r8q, version-sdk = 33, version-os = samsung/r8qsqx/r8q:13/TP1A.220624.014/G781USQUCHWH4:user/release-keys)

(e, ExceptionActivity, 2024-09-14 17:49:55): Uncaught exception ("Unknown Context"): [Youtube] Login required
Reason: Sign in to confirm you’re not a bot (421)[3-4]

com.futo.platformplayer.engine.exceptions.ScriptException: [Youtube] Login required
Reason: Sign in to confirm you’re not a bot (421)[3-4]
	at com.futo.platformplayer.constructs.BatchedTaskHandler$execute$1$task$1.invokeSuspend(BatchedTaskHandler.kt:62)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@96f8854, [Dispatchers.IO](http://dispatchers.io/)]
Caused by: com.caoccao.javet.exceptions.JavetExecutionException: Error: Login required
Reason: Sign in to confirm you’re not a bot
	at com.caoccao.javet.interop.V8Native.scriptExecute(Native Method)
	at com.caoccao.javet.interop.V8Runtime.execute(V8Runtime.java:928)
	at com.caoccao.javet.interop.executors.V8StringExecutor.execute(V8StringExecutor.java:107)
	at com.caoccao.javet.interop.IV8Executable.execute(IV8Executable.java:44)
	at com.futo.platformplayer.engine.V8Plugin$executeTyped$2.invoke(V8Plugin.kt:220)
	at com.futo.platformplayer.engine.V8Plugin$executeTyped$2.invoke(V8Plugin.kt:219)
	at com.futo.platformplayer.engine.V8Plugin$Companion.catchScriptErrors(V8Plugin.kt:294)
	at com.futo.platformplayer.engine.V8Plugin.catchScriptErrors(V8Plugin.kt:269)
	at com.futo.platformplayer.engine.V8Plugin.executeTyped(V8Plugin.kt:219)
	at com.futo.platformplayer.api.media.platforms.js.JSClient$getContentDetails$1.invoke(JSClient.kt:520)
	at com.futo.platformplayer.api.media.platforms.js.JSClient$getContentDetails$1.invoke(JSClient.kt:517)
	at com.futo.platformplayer.api.media.platforms.js.JSClient.isBusyWith(JSClient.kt:733)
	at com.futo.platformplayer.api.media.platforms.js.JSClient.getContentDetails(JSClient.kt:517)
	at com.futo.platformplayer.states.StatePlatform$_batchTaskGetVideoDetails$1.invokeSuspend(StatePlatform.kt:117)
	at com.futo.platformplayer.states.StatePlatform$_batchTaskGetVideoDetails$1.invoke(Unknown Source:8)
	at com.futo.platformplayer.states.StatePlatform$_batchTaskGetVideoDetails$1.invoke(Unknown Source:4)
	at com.futo.platformplayer.constructs.BatchedTaskHandler$execute$1$task$1.invokeSuspend(BatchedTaskHandler.kt:55)
	... 6 more

_No response_

**Comment by Noisy-Koi** [comment]
I have also been getting this issue, I didn't realize it may be related to my VPN (proton VPN) but most videos tend to reach some specific point and just restart the video with a message "Block attempt".

It doesn't seem to be every video but tends to be the same videos at the same point in those videos.

**Comment by dimyself** [comment]
I've been getting this error for awhile using Nordvpn. Its been getting worse over the weeks. 

Now most ip's / countries are blocked by youtube "login required".

On my desktop linux youtube site (in private mode or logged in) works fine using vpn Nordvpn.

But  youtube apps (grayjay, newpipe, etc) require login on phone and desktop.

**Comment by dimyself** [comment]
> I have also been getting this issue, I didn't realize it may be related to my VPN (proton VPN) but most videos tend to reach some specific point and just restart the video with a message "Block attempt".
> 
> It doesn't seem to be every video but tends to be the same videos at the same point in those videos.

For me it consistently occurs either right away at the beginning of video, or at the 1 minute mark.

**Comment by Zvonimir-FUTO** [comment]
This should be fixed in the latest version of Grayjay and Youtube (v227). Could you retest?

**Comment by TheShanMan** [comment]
Is there a brand new version of Grayjay? I wasn't prompted to update Grayjay but I updated Youtube to 227 and I still can't watch without logging in, which AFAIK is still because of being on a vpn.

**Comment by Zvonimir-FUTO** [comment]
Well when the issue was opened Grayjay was on 264 so 281 is upgrade from that. If you updated recently then no, there is no brand new version. Can you not watch any videos on VPN?

**Comment by TheShanMan** [comment]
I haven't been able to watch any youtube videos on vpn since they started clamping down. My workaround has been to use a dedicated browser to access youtube.com directly. That works for me on a vpn. I can also use newpipe on mobile with no vpn (but not grayjay). That tells me they disfavor 3rd party clients, as well as vpns, and youtube dislikes grayjay more than newpipe for whatever reason. It almost seems like they have a scoring system and if your score crosses a threshold, they force you to log in.

**Comment by Zvonimir-FUTO** [comment]
We released a new version with improved Youtube Session client which should result in being detected as bot less then before.

Of course, being logged in, providing Youtube activity and using login for video details would help with that but we are aware many of you avoid those options out of privacy reasons.

Please test a bit more and tell us what you found.

**Comment by SunnySapphire** [comment]
> We released a new version with improved Youtube Session client which should result in being detected as bot less then before.
> 
> Of course, being logged in, providing Youtube activity and using login for video details would help with that but we are aware many of you avoid those options out of privacy reasons.
> 
> Please test a bit more and tell us what you found.

![Screenshot_20250724_151029_Grayjay.jpg](https://github.com/user-attachments/assets/4788301e-5c58-449a-bbc6-5ec6b175d323)
The session client worked for some videos, they loaded but took a bit longer, but I still get the error where it wants me to sign in to prove i'm not a robot

**Comment by Zvonimir-FUTO** [comment]
@SunnySapphire to confirm this is with VPN right? Also do you get that for specific videos or just after a while? Does switching VPN servers helps?

**Comment by SunnySapphire** [comment]
> @SunnySapphire to confirm this is with VPN right? Also do you get that for specific videos or just after a while? Does switching VPN servers helps?

Yes, i have a vpn on, it just seems to happen after awhile, and switching servers doesnt seem to do much, ans some videos load perfectly without needing to use the session client while others needed to use it

**Comment by SunnySapphire** [comment]
@Zvonimir-FUTO new error it is now is saying every video i try to click on is unavailable for some reason![Screenshot_20250724_185108_Grayjay.jpg](https://github.com/user-attachments/assets/23bb8034-d7cd-48f5-ad99-7cd1dc7158e1)

**Comment by SunnySapphire** [comment]
Okay so i have tested multiple different vpn servers at different locations and all cause every video to say its not available, as soon as i turn off my vpn videos work

**Comment by Anderslv** [comment]
I also run into the 'log in to prove that I am not a robot' error message. I'm wondering if this is a solution generated by the FUTO team, or if it is the direct message from YouTube? When I get the message, I can close it down to try to go to the YouTube page through the button called 'page', though, the whole interface seems to be unavailable while GrayJay is trying once again to establish the feed. My thought was, that on the YouTube page, when this kind of prompt happens, it usually results in some kind of CHAPTA challenge, and my hope was.that I might just be able to complete the challenge on the page. Would this be possible?

**Comment by SunnySapphire** [comment]
> I also run into the 'log in to prove that I am not a robot' error message. I'm wondering if this is a solution generated by the FUTO team, or if it is the direct message from YouTube? When I get the message, I can close it down to try to go to the YouTube page through the button called 'page', though, the whole interface seems to be unavailable while GrayJay is trying once again to establish the feed. My thought was, that on the YouTube page, when this kind of prompt happens, it usually results in some kind of CHAPTA challenge, and my hope was.that I might just be able to complete the challenge on the page. Would this be possible?

From my experience if you open the youtube website without being logged in while having a vpn on or while in private browsing it asks you to login to prove you are not a bot to watch videos.

**Comment by Anderslv** [comment]
I see. Then I guess, making a google account under a fake name, using a VOIP phonenumber and an email alias, will be my next suggestion in an attempt at trying to watch YouTube without the surveillance. 

For me, btw, I can usually watch a good amount of YouTube through GrayJay before they flag me. It seems that most other users get blocked faster? I also use Proton VPN on Samsung Galagy S22 Plus.

**Comment by SunnySapphire** [comment]
That wouldn't be better either I believe because even under a fake name google will still collect a lot of data about you and spy on you.

For me atleast i get blocked anytime I turn on my vpn, i use a samsung galaxy s20 and mullvad vpn.

**Comment by shyshycat** [comment]
Not using any kind of VPN and this only appears on age restricted content

**Comment by SunnySapphire** [comment]
I gave up and logged in with a burner account and i still get an error saying the video is not available while on a VPN even though i am signed in and it happens on almost every video

**Comment by shyshycat** [comment]
> I gave up and logged in with a burner account and i still get an error saying the video is not available while on a VPN even though i am signed in and it happens on almost every video

So same as me age restricted or what? Kinda feels sad

**Comment by dimyself** [comment]
I use proton vpn. every video I have to change servers in proton. sometimes
I have to switch servers multiple times to play a video. many times, it
will play the first 1min of video, then stop. Then have to switch servers
and reload the video.

On Grayjay desktop, I don't have any issues loading videos on proton vpn. I
don't know what the difference is, why one loads and not the other? On
proton desktop, I have access to many more servers, but still... It looks
like theres some kind of security check on the mobile client that isn't on
the desktop client... As i don't get loading errors on desktop grayjay

**Comment by NanNam226** [comment]
For me, the following steps currently gives me longer streaks of free uninterrupted youtube stream-time. We're talking hours or sometimes a full day. 

- Clear Channel cache in settings 
- Clear cookies in settings
- Close down the app
- Open the Android app settings for GrayJay
- Press stop app
- Clear cache
- Close all other open apps through the close all function during app-switching
- Change server in Proton VPN
- Open GrayJay 
- Clear cookies once again because of superstition
- Go to subscriptions view in GrayJay and pull down to make it update the feed
- Watch youtube without being identified as a VPN user for hours at a time
- If it didn't work, do it again. Then it usually works the second time around.

For streaming on HBO in Brave, I had this same issue. I turned out to be because I somehow had allowed HBO to let its cookies survive in the browser from session to session, thereby allowing my information spill through the data stored on those cookies. Deleting all cookies and then activating the setting: 'delete cookies for a website when I close that site' fixed the issue. Now I just have to actually close the HBO tab once in a while, and I have no issues.

The reason for some of the steps are purely based on thoughts of correlatin snitching traffic, meybe letting google couple your new network activities with your previous ones purely bases on your network fingerprint. I don't know if this has any real effect. I just stuck with the protocol after I implemented a few extra steps and found that it was way more effective than before 😅
