### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by lessthelonely** [futo-org/grayjay-android#146]
The context: tried opening an Alpharad video, from YouTube. It keeps crashing on opening, can't even see the video.

Might be a me issue, but I figured I should share.

``
Version information (version_name = 181, version_code = 181, flavor = stable, build_type = release)
Device information (brand= HONOR, manufacturer = HUAWEI, device = HWLLD-H, version-sdk = 28, version-os = HONOR/LLD-L21/HWLLD-H:9/HONORLLD-L21/9.1.0.124C636:user/release-keys)

(e, ExceptionActivity, 2023-11-01 12:06:03): Uncaught exception ("Unknown Context"): Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2ef3da0 u0 com.futo.platformplayer/.services.MediaPlaybackService}

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2ef3da0 u0 com.futo.platformplayer/.services.MediaPlaybackService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2126)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7625)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
``

**Comment by Alexander3a** [comment]
Same issue here in every video
On s8 stock

**Comment by Goracij** [comment]
> Same issue here on every video On s8 stock

Same phone model (samsung s8 stock), same issue - exception throw on any video playback attempt (have only youtube subscriptions imported).

Version information (version_name = 190, version_code = 190, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = dreamlte, version-sdk = 28, version-os = )

(e, ExceptionActivity, 2023-11-06 17:57:04): Uncaught exception ("Unknown Context"): Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3fe6f8b u0 com.futo.platformplayer/.services.MediaPlaybackService}

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{3fe6f8b u0 com.futo.platformplayer/.services.MediaPlaybackService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7050)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by usertoroot** [comment]
Fixed in build 191, releasing soon.

**Comment by koen-futo** [comment]
Fixed in build 191, releasing soon.
