### ISSUE TITLE
Crash immediately after update to v267

### ISSUE THREAD

**Issue by Mattrazol** [futo-org/grayjay-android#1550]
Hello devs.
I am having issues with the app after the latest update to v267. The app crashes immediately with this error:
```
Version information (version_name = 267, version_code = 267, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = panther, version-sdk = 35, version-os = )

(e, ExceptionActivity, 2024-12-05 16:50:48): Uncaught exception ("Unknown Context"): Inconsistency detected. Invalid item position 1(offset:1).state:2 androidx.recyclerview.widget.RecyclerView{12506a5 VFED..... ......I. 0,0-0,0 #7f0a030f app:id/list_results}, adapter:com.futo.platformplayer.views.adapters.feedtypes.PreviewContentListAdapter@74144b, layout:androidx.recyclerview.widget.GridLayoutManager@6046821, context:com.futo.platformplayer.activities.MainActivity@778b9c8

java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid item position 1(offset:1).state:2 androidx.recyclerview.widget.RecyclerView{12506a5 VFED..... ......I. 0,0-0,0 #7f0a030f app:id/list_results}, adapter:com.futo.platformplayer.views.adapters.feedtypes.PreviewContentListAdapter@74144b, layout:androidx.recyclerview.widget.GridLayoutManager@6046821, context:com.futo.platformplayer.activities.MainActivity@778b9c8
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6821)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6757)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6753)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:584)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:182)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4645)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:4022)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28122)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:705)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:100)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2381)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1240)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28122)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:452)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:750)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:551)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:486)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solvingPass(Direct.java:224)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:693)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:2936)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1608)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:878)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6989)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:719)
	at android.view.View.measure(View.java:28122)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4823)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3220)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3525)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2917)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10324)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1406)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:945)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by Zvonimir-FUTO** [comment]
Please update to v268 where issue should be fixed.
