### ISSUE TITLE
Multi User Crash

### ISSUE THREAD

**Issue by McIrco95** [futo-org/grayjay-android#1555]
### What happened?

When starting the app while it is alredy running in another android user profile it crashes

### Grayjay Version

268

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Version information (version_name = 268, version_code = 268, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = husky, version-sdk = 35, version-os = )

(e, ExceptionActivity, 2024-12-05 22:30:58): Uncaught exception ("Unknown Context"): bind failed: EADDRINUSE (Address already in use)

java.net.BindException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.IoBridge.bind(IoBridge.java:149)
	at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
	at java.net.ServerSocket.bind(ServerSocket.java:399)
	at java.net.ServerSocket.<init>(ServerSocket.java:259)
	at java.net.ServerSocket.<init>(ServerSocket.java:151)
	at com.futo.platformplayer.states.StateSync.start$lambda$2(StateSync.kt:115)
	at com.futo.platformplayer.states.StateSync.$r8$lambda$nTBjXj4h52n1JvKkkOk237EkUpQ(Unknown Source:0)
	at com.futo.platformplayer.states.StateSync$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.Linux.bind(Native Method)
	at libcore.io.ForwardingOs.bind(ForwardingOs.java:138)
	at libcore.io.ForwardingOs.bind(ForwardingOs.java:138)
	at libcore.io.IoBridge.bind(IoBridge.java:145)
	... 9 more
```

**Comment by koen-futo** [comment]
Hey, made a fix for this just now. Will be released with then next build. As a temporary workaround you can go to Settings -> Synchronization -> Enabled

And make sure it is disabled.

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in v276.
