### ISSUE TITLE
crash on launch

### ISSUE THREAD

**Issue by palgume123** [futo-org/grayjay-android#158]
here's the full log, I don't really know what's causing this

Version information (version_name = 181, version_code = 181, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = panther, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2023-11-02 12:17:33): Uncaught exception ("Unknown Context"): Empty error

javax.crypto.AEADBadTagException
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:626)
	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
	at com.futo.polycentric.core.EncryptionProvider.decrypt(EncryptionProvider.kt:44)
	at com.futo.polycentric.core.SqlLiteStore.getProcessSecret(SqlLiteStore.kt:133)
	at com.futo.platformplayer.states.StatePolycentric.load(StatePolycentric.kt:61)
	at com.futo.platformplayer.states.StateApp.mainAppStarting(StateApp.kt:355)
	at com.futo.platformplayer.activities.MainActivity.onCreate(MainActivity.kt:159)
	at android.app.Activity.performCreate(Activity.java:8595)
	at android.app.Activity.performCreate(Activity.java:8573)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3764)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3922)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2443)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
Caused by: android.security.KeyStoreException: Signature/MAC verification failed (internal Keystore code: -30 message: system/security/keystore2/src/operation.rs:850: KeystoreOperation::finish

Caused by:
    0: system/security/keystore2/src/operation.rs:426: Finish failed.
    1: Error::Km(r#VERIFICATION_FAILED)) (public error code: 10 internal Keystore code: -30)
	at android.security.KeyStore2.getKeyStoreException(KeyStore2.java:386)
	at android.security.KeyStoreOperation.handleExceptions(KeyStoreOperation.java:78)
	at android.security.KeyStoreOperation.finish(KeyStoreOperation.java:128)
	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer$MainDataStream.finish(KeyStoreCryptoOperationChunkedStreamer.java:228)
	at android.security.keystore2.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:181)
	at android.security.keystore2.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:396)
	at android.security.keystore2.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:618)
	... 22 more

**Comment by gingernate** [comment]
I've had the same issue. Clearing cache doesn't help. Resetting the app data fixes the issue

**Comment by palgume123** [comment]
> I've had the same issue. Clearing cache doesn't help. Resetting the app data fixes the issue

wtf thank you so much I didn't think of that. I even reinstalled the app a couple of times and thought that clearing the data won't help because reinstalling didn't.
