### ISSUE TITLE
Commenting under a comment crashes the app

### ISSUE THREAD

**Issue by VoxelPrismatic** [futo-org/grayjay-android#1583]
### What happened?

1. Find a comment
2. Comment under that comment
3. \*crash\*

https://github.com/user-attachments/assets/71c7ceba-57de-472d-aaaf-918555a00d97

### Grayjay Version

268

### What plugins are you seeing the problem on?

Youtube

### Plugin Version

218

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Version information (version_name = 268, version_code = 268, flavor = stable, build_type = release)
Device information (brand= Sony, manufacturer = Sony, device = XQ-DQ62, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-12-09 20:03:12): Uncaught exception ("Unknown Context"): Index -1 out of bounds for length 2

java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 2
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.util.Objects.checkIndex(Objects.java:359)
	at java.util.ArrayList.set(ArrayList.java:477)
	at com.futo.platformplayer.views.segments.CommentsList.replaceComment(CommentsList.kt:271)
	at com.futo.platformplayer.fragment.mainactivity.main.VideoDetailView$62$2.invoke(VideoDetailView.kt:736)
	at com.futo.platformplayer.fragment.mainactivity.main.VideoDetailView$62$2.invoke(VideoDetailView.kt:731)
	at com.futo.platformplayer.views.overlays.RepliesOverlay$1.invoke(RepliesOverlay.kt:75)
	at com.futo.platformplayer.views.overlays.RepliesOverlay$1.invoke(RepliesOverlay.kt:73)
	at com.futo.platformplayer.constructs.Event1.emit(Event.kt:99)
	at com.futo.platformplayer.views.comments.AddCommentView$1$1$1.invoke(AddCommentView.kt:36)
	at com.futo.platformplayer.views.comments.AddCommentView$1$1$1.invoke(AddCommentView.kt:36)
	at com.futo.platformplayer.UIDialogs$Companion$showCommentDialog$2.invoke(UIDialogs.kt:503)
	at com.futo.platformplayer.UIDialogs$Companion$showCommentDialog$2.invoke(UIDialogs.kt:503)
	at com.futo.platformplayer.constructs.Event1.emit(Event.kt:99)
	at com.futo.platformplayer.dialogs.CommentDialog.onCreate$lambda$1(CommentDialog.kt:114)
	at com.futo.platformplayer.dialogs.CommentDialog.$r8$lambda$Ch6uELb6tLO7Kybqhlib27OXS-I(Unknown Source:0)
	at com.futo.platformplayer.dialogs.CommentDialog$$ExternalSyntheticLambda1.onClick(D8$$SyntheticClass:0)
	at android.view.View.performClick(View.java:7670)
	at android.view.View.performClickInternal(View.java:7644)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30175)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
```

**Comment by Zvonimir-FUTO** [comment]
Thank you for reporting, we are investigating this.

**Comment by VoxelPrismatic** [comment]
I forgot to add that the comment does actually post, so it may be a rendering issue.

**Comment by Zvonimir-FUTO** [comment]
The fix will be released in the next version of Grayjay.

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in v276.
