### ISSUE TITLE
App crash, possibly intentional bug/issue 

### ISSUE THREAD

**Issue by UnknownUsernme** [futo-org/grayjay-android#1585]
### What happened?

Quick disclaimer I have both this version and the Google play store version of the app installed. When one of the greyjey apps is on and the second version is launched it will immediately crash. The order in which app is launched first does not matter and this crash ONLY happens when more than one greyjey app is running and the crash/error did not occur on the previous app version. Also sorry for the poor screen recording quality had to get it under 10MB
![Screenshot_20241209_145605_Grayjay](https://github.com/user-attachments/assets/07001e7b-b2eb-45f5-8441-ecbab0ce58d9)
![Screenshot_20241209_145610_Grayjay](https://github.com/user-attachments/assets/4151c367-d61a-47fa-845b-66b707dac7fe)
![Screenshot_20241209_160258_One UI Home](https://github.com/user-attachments/assets/b0bad9ad-5f48-4ecc-ab20-b80aefe33be1)

https://github.com/user-attachments/assets/8792b53d-1ea3-4e80-92d8-8ab8bbbc1d19

### Grayjay Version

268

### What plugins are you seeing the problem on?

Other

### Plugin Version

N/A

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

### Relevant log output

```shell
Version information (version_name = 268, version_code = 268, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = a54x, version-sdk = 34, version-os = samsung/a54xue/a54x:14/UP1A.231005.007/A546U1UEU8CXH1:user/release-keys)

(e, ExceptionActivity, 2024-12-09 19:44:11): Uncaught exception ("Unknown Context"): bind failed: EADDRINUSE (Address already in use)

java.net.BindException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.IoBridge.bind(IoBridge.java:149)
	at java.net.PlainSocketImpl.socketBind(PlainSocketImpl.java:162)
	at java.net.AbstractPlainSocketImpl.bind(AbstractPlainSocketImpl.java:427)
	at java.net.ServerSocket.bind(ServerSocket.java:399)
	at java.net.ServerSocket.<init>(ServerSocket.java:259)
	at java.net.ServerSocket.<init>(ServerSocket.java:151)
	at com.futo.platformplayer.states.StateSync.start$lambda$2(StateSync.kt:115)
	at com.futo.platformplayer.states.StateSync.$r8$lambda$nTBjXj4h52n1JvKkkOk237EkUpQ(Unknown Source:0)
	at com.futo.platformplayer.states.StateSync$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.ErrnoException: bind failed: EADDRINUSE (Address already in use)
	at libcore.io.Linux.bind(Native Method)
	at libcore.io.ForwardingOs.bind(ForwardingOs.java:138)
	at libcore.io.ForwardingOs.bind(ForwardingOs.java:138)
	at libcore.io.IoBridge.bind(IoBridge.java:145)
	... 9 more
```

**Comment by Zvonimir-FUTO** [comment]
Seems to be same as #1555.

https://github.com/futo-org/grayjay-android/issues/1555#issuecomment-2523721504
> Hey, made a fix for this just now. Will be released with then next build. As a temporary workaround you can go to Settings -> Synchronization -> Enabled
> 
> And make sure it is disabled.

**Comment by UnknownUsernme** [comment]
Ok,  thanks. Disabling synchronization in both apps fixed the crash
