### ISSUE TITLE
App randomly crashes

### ISSUE THREAD

**Issue by Fl1ck5h07** [futo-org/grayjay-android#1599]
### What happened?

Just as the title says, the app, as far as I understand, randomly crashes without any influence from the user (I think). Sometimes it crashes in the middle of a video, sometimes just after starting the app. Sometimes it seems that if the app crashes and I restart it it has a bigger chance to crash fast, but sometimes it takes hours until the next crash.

I submitted the crash log, which seems to be the same every time, quite a lot of times, but here it is:
Unhandled exception in VS
Version information (version_name = 268, version_code = 268, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = a54x, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-12-11 23:29:48): Uncaught exception ("Unknown Context"): Empty error

java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:792)
	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:790)
	at com.futo.platformplayer.mdns.ServiceRecordAggregator.getCurrentServices(ServiceRecordAggregator.kt:367)
	at com.futo.platformplayer.mdns.ServiceRecordAggregator.access$getCurrentServices(ServiceRecordAggregator.kt:42)
	at com.futo.platformplayer.mdns.ServiceRecordAggregator$start$1$1.invokeSuspend(ServiceRecordAggregator.kt:66)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@ab5c956, Dispatchers.Default]

### Grayjay Version

268

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in the upcoming version of Grayjay.

**Comment by Zvonimir-FUTO** [comment]
This has been fixed in v276.
