### ISSUE TITLE
App Non-Functional

### ISSUE THREAD

**Issue by Stormhammer1399** [futo-org/grayjay-android#1626]
### What happened?

After updating GrayJay, the app became unresponsive. It refuses to open beyond an error message screen. I have included the relevant info from that screen below.

### Grayjay Version

277

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Version information (version_name = 277, version_code = 277, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = oriole, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-12-19 19:48:09): Uncaught exception ("Unknown Context"): sources/apple-podcasts/ApplePodcastsConfig.json

java.io.FileNotFoundException: sources/apple-podcasts/ApplePodcastsConfig.json
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:917)
	at android.content.res.AssetManager.open(AssetManager.java:894)
	at com.futo.platformplayer.states.StateAssets$Companion.readAsset(StateAssets.kt:49)
	at com.futo.platformplayer.states.StatePlugins.getEmbeddedPluginConfig(StatePlugins.kt:273)
	at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins(StatePlugins.kt:244)
	at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins$default(StatePlugins.kt:242)
	at com.futo.platformplayer.states.StatePlatform$updateAvailableClients$2.invokeSuspend(StatePlatform.kt:197)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by judgejarv** [comment]
I have the same

**Comment by pauel3312** [comment]
lmao there were 3 duplicates of this posted within 3 minutes
I love this community (#1627 and #1628 )

**Comment by pauel3312** [comment]
I think this is the prime example of why we need a way to revert to an old version, BC I can't find one rn...

**Comment by Zvonimir-FUTO** [comment]
We apologize for the inconvenience, we are investigating the issue.

**Comment by SirRGB** [comment]
Same on Xperia 5 mk2, Android 13 (leaf os, microg, custom)

**Comment by palmerbomber1** [comment]
I feel like a reinstall when its fixed is the only way to get past this error screen, as tapping on "check for updates" just gives an "failed to check for updates" error

**Comment by cyraid** [comment]
Seems like it can't read ApplePodcastsConfig.json .. Perhaps a try/catch around it to gracefully error out for file reads? Maybe the ApplePodcastsConfig.json wasn't provided in the apk?

**Comment by Zvonimir-FUTO** [comment]
Hi everyone we found the cause and fixed it. Please download the apk manually from https://grayjay.app/ since **Check for update** on crash screen seems to be broken as well :(
