### ISSUE TITLE
Crash on startup After update (Version 277)

### ISSUE THREAD

**Issue by pauel3312** [futo-org/grayjay-android#1627]
### What happened?

I launch the app, the screen shift left to right ant right to left, and then the app just closes. I have no bug report screen. I could access it once by going back to the app without relaunching it, or something, with the quick app change on my device.

### Grayjay Version

277

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

### Relevant log output

```shell
Version information (version_name = 277, version_code = 277, flavor = stable, build_type = release)
Device information (brand= Xiaomi, manufacturer = Xiaomi, device = perseus, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-12-19 19:53:15): Uncaught exception ("Unknown Context"): sources/apple-podcasts/ApplePodcastsConfig.json

java.io.FileNotFoundException: sources/apple-podcasts/ApplePodcastsConfig.json
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:919)
	at android.content.res.AssetManager.open(AssetManager.java:896)
	at com.futo.platformplayer.states.StateAssets$Companion.readAsset(StateAssets.kt:49)
	at com.futo.platformplayer.states.StatePlugins.getEmbeddedPluginConfig(StatePlugins.kt:273)
	at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins(StatePlugins.kt:244)
	at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins$default(StatePlugins.kt:242)
	at com.futo.platformplayer.states.StatePlatform$updateAvailableClients$2.invokeSuspend(StatePlatform.kt:197)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by pauel3312** [comment]
My device is a Xiaomi Mi Mix 3 running the latest LineageOS (29, build number: lineage_perseus-userdebug 14 AP2A.240905.003 7b5474a026)

**Comment by judgejarv** [comment]
Same here

**Comment by pauel3312** [comment]
duplicate of #1626
