### ISSUE TITLE
Crash when opening the app

### ISSUE THREAD

**Issue by micrusa** [futo-org/grayjay-android#1628]
### What happened?

The app crashes immediately after opening it after I updated it. Removing app data doesn't fix the issue

### Grayjay Version

277

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [X] N/A

### Relevant log output

```shell
2024-12-19 20:42:52.004 6624 6624 com.futo.platformplayer E AndroidRuntime : FATAL EXCEPTION: main
Process: com.futo.platformplayer, PID: 6624
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.futo.platformplayer/com.futo.platformplayer.activities.MainActivity}: java.io.FileNotFoundException: sources/apple-podcasts/ApplePodcastsConfig.json
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3783)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3923)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2444)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8223)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:977)
Caused by: java.io.FileNotFoundException: sources/apple-podcasts/ApplePodcastsConfig.json
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:908)
	at android.content.res.AssetManager.open(AssetManager.java:885)
	at com.futo.platformplayer.states.StateAssets$Companion.readAsset(StateAssets.kt:49)
	at com.futo.platformplayer.states.StatePlugins.getEmbeddedPluginConfig(StatePlugins.kt:273)
	at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins(StatePlugins.kt:244)
	at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins$default(StatePlugins.kt:242)
	at com.futo.platformplayer.states.StatePlatform$updateAvailableClients$2.invokeSuspend(StatePlatform.kt:197)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by cyraid** [comment]
Yup. Someone/something definitely got borked. Completely unusable now. Can't even check for updates. Perhaps there should be a failsafe from this in the future? Something to do with Apple Podcasts. I think the exception is it's missing the ApplePodcastsConfig.json. Definitely should've been wrapped with a try/catch on all file reads for a graceful failure expectation.

**Comment by micrusa** [comment]
duplicate of #1626
