### ISSUE TITLE
BUG: Latest update crashes on startup

### ISSUE THREAD

**Issue by Nacandcheese** [futo-org/grayjay-android#1632]
### What happened?

Immediately after update, Grayjay fails to load, boot, or anything without tossing the error uploaded in the log output section. The app refuses to let me go past the error log either. 

### Grayjay Version

277

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [ ] While logged in
- [ ] While logged out
- [ ] N/A

### Relevant log output

```shell
Version information (version_name = 277, version_code = 277, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = a02q, version-sdk = 31, version-os = samsung/a02quc/a02q:12/SP1A.210812.016/A025AUCU5CWF1:user/release-keys)

(e, ExceptionActivity, 2024-12-20 01:15:41): Uncaught exception ("Unknown Context"): sources/apple-podcasts/ApplePodcastsConfig.json

java.io.FileNotFoundException: sources/apple-podcasts/ApplePodcastsConfig.json
	at android.content.res.AssetManager.nativeOpenAsset(Native Method)
	at android.content.res.AssetManager.open(AssetManager.java:939)
	at android.content.res.AssetManager.open(AssetManager.java:916)
	at com.futo.platformplayer.states.StateAssets$Companion.readAsset(StateAssets.kt:49)
	at com.futo.platformplayer.states.StatePlugins.getEmbeddedPluginConfig(StatePlugins.kt:273)
	at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins(StatePlugins.kt:244)
	at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins$default(StatePlugins.kt:242)
	at com.futo.platformplayer.states.StatePlatform$updateAvailableClients$2.invokeSuspend(StatePlatform.kt:197)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Nordlicht-13** [comment]
Confirm this on my Pixel 5 with Graphene OS.

**Comment by alfkonee** [comment]
Same issue here on a Samsung A54

**Comment by Zvonimir-FUTO** [comment]
Hi everyone we found the cause and fixed it. Please download the apk manually from https://grayjay.app/ since Check for update on crash screen seems to be broken as well :(
