### ISSUE TITLE
App crash on startup after new update

### ISSUE THREAD

**Issue by zifnabb** [futo-org/grayjay-android#1637]
### What happened?

Updated app yesterday (in-app) and now it flickers, then  crashes on boot.
Doesn't make it to the plugins, only two I use are twitch and YouTube.
I see it fails while referring to an ApplePodcasts.json , I didn't even know this app supported that.

https://github.com/user-attachments/assets/94ce7ccd-d795-4cd8-b51e-7c2ece0e3923

### Grayjay Version

277

### What plugins are you seeing the problem on?

All

### When do you experience the issue?

- [X] While logged in
- [X] While logged out
- [X] N/A

### Relevant log output

```shell
Version information (version_name = 277, version_code = 277, flavor = stable, build_type = release)
Device information (brand= OnePlus, manufacturer = OnePlus, device = OP594DL1, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-12-20 19:58:00): Uncaught exception ("Unknown Context"): sources/apple-podcasts/ApplePodcastsConfig.json

java.io.FileNotFoundException: sources/apple-podcasts/ApplePodcastsConfig.json
    at android.content.res.AssetManager.nativeOpenAsset(Native Method)
    at android.content.res.AssetManager.open(AssetManager.java:940)
    at android.content.res.AssetManager.open(AssetManager.java:917)
    at com.futo.platformplayer.states.StateAssets$Companion.readAsset(StateAssets.kt:49)
    at com.futo.platformplayer.states.StatePlugins.getEmbeddedPluginConfig(StatePlugins.kt:273)
    at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins(StatePlugins.kt:244)
    at com.futo.platformplayer.states.StatePlugins.updateEmbeddedPlugins$default(StatePlugins.kt:242)
    at com.futo.platformplayer.states.StatePlatform$updateAvailableClients$2.invokeSuspend(StatePlatform.kt:197)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by Zvonimir-FUTO** [comment]
Hi, we found the cause and fixed it. Please download the apk manually from https://grayjay.app/ since **Check for update** on crash screen seems to be broken as well :(

Note that you don't need to uninstall the previous app nor wipe any data. Just update over it.
