### ISSUE TITLE
App keeps on randomly crashing when opening it

### ISSUE THREAD

**Issue by cindrmon** [futo-org/grayjay-android#173]
When I try opening the app for the first time (or loading it up back again while multitasking from another app), it would sometimes crash, even multiple times at once. Sometimes it works fine, sometimes the app won't load and crash. Even clearing the app cache several times, closing all apps that are in the background (incl. the Grayjay app), and even restarting my phone would cause this random crashing.

For additional information, this is what I would frequently get when launching the app:

```
Version information (version_name = 181, version_code = 181, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = a12, version-sdk = 31, version-os = samsung/a12nnxx/a12:12/SP1A.210812.016/A125FXXU2CWB1:user/release-keys)

(e, ExceptionActivity, 2023-11-04 15:49:16): Uncaught exception ("Unknown Context"): Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{46347cd u0 com.futo.platformplayer/.services.ExportingService}

android.app.ForegroundServiceDidNotStartInTimeException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{46347cd u0 com.futo.platformplayer/.services.ExportingService}
	at android.app.ActivityThread.throwRemoteServiceException(ActivityThread.java:2147)
	at android.app.ActivityThread.access$2800(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2376)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

You may also freely mark as duplicate if ever someone else has a similar issue. I just want to get this out as I don't know if someone made a concern of the app randomly crashing when launching it.

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
