### ISSUE TITLE
App crashes on galaxy fold when started unfolded

### ISSUE THREAD

**Issue by obsgolem** [futo-org/grayjay-android#174]
If I start the app while my phone is unfolded, it crashes immediately. Error is below:
```
Version information (version_name = 181, version_code = 181, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = q2q, version-sdk = 33, version-os = samsung/q2quew/q2q:13/TP1A.220624.014/F926U1UEU4GWH5:user/release-keys)

(e, ExceptionActivity, 2023-11-04 16:37:36): Uncaught exception ("Unknown Context"): Index: 1, Size: 0

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.rangeCheckForAdd(ArrayList.java:763)
	at java.util.ArrayList.add(ArrayList.java:488)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.updateMoreButtons(MenuBottomBarFragment.kt:228)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.updateAllButtonVisibility(MenuBottomBarFragment.kt:259)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.updateButtonDefinitions(MenuBottomBarFragment.kt:306)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.<init>(MenuBottomBarFragment.kt:103)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment.onCreateView(MenuBottomBarFragment.kt:42)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
	at android.app.Activity.performStart(Activity.java:8682)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4219)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
