### ISSUE TITLE
Crash in the creators tab

### ISSUE THREAD

**Issue by callmeTayyy** [futo-org/grayjay-android#199]
After I updated to version 190, the app gives an error when trying to access the creators tab (see error message below) and I have to restart the app.

Updated from v181 to v190 using the arm64-v8a APK from the website.

- Phone: Samsung A54 5G
- Model: SM-A546E/DS
- Android 13 + One UI 5.1

Error message:

```
Version information (version_name = 190, version_code = 190, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = a54x, version-sdk = 33, version-os = samsung/a54xnsxx/a54x:13/TP1A.220624.014/A546EXXU5AWHD:user/release-keys)

(e, ExceptionActivity, 2023-11-06 21:49:43): Uncaught exception ("Contexto desconhecido"): length=2; index=3

java.lang.ArrayIndexOutOfBoundsException: length=2; index=3
	at java.util.Arrays$ArrayList.get(Arrays.java:4210)
	at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:394)
	at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:450)
	at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
	at android.widget.Spinner.makeView(Spinner.java:776)
	at android.widget.Spinner.layout(Spinner.java:723)
	at android.widget.Spinner.onLayout(Spinner.java:685)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1818)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1584)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at androidx.appcompat.widget.Toolbar.layoutChildLeft(Toolbar.java:2207)
	at androidx.appcompat.widget.Toolbar.onLayout(Toolbar.java:2146)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1829)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1673)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1582)
	at com.google.android.material.appbar.AppBarLayout.onLayout(AppBarLayout.java:553)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.appbar.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:66)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1768)
	at com.google.android.material.appbar.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:1427)
	at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1446)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:332)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:270)
	at android.view.View.layout(View.java:24969)
	at android.view.ViewGroup.layout(ViewGroup.java:6784)
	at androidx.constraintlayout.motion.widget.MotionPaths.setView(MotionPaths.java:640)
	at androidx.constraintlayout.motion.widget.MotionController.interpolate(MotionController.java:1286)
	at androidx.constraintlayout.motion.widget.MotionLayout.evaluateLayout(MotionLayout.java:3572)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:2960)
	at android.view.View.measure(View.java:27731)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:27731)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27731)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:27731)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:27731)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7352)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:1379)
	at android.view.View.measure(View.java:27731)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4841)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:3426)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3732)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3116)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:10885)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1301)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1309)
	at android.view.Choreographer.doCallbacks(Choreographer.java:923)
	at android.view.Choreographer.doFrame(Choreographer.java:852)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1283)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8762)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
```

**Comment by koen-futo** [comment]
Fixed in version 191.
