### ISSUE TITLE
Galaxy Fold: Crashes on launch when Unfolded.  Launches fine when "Folded".

### ISSUE THREAD

**Issue by BrotherPanan** [futo-org/grayjay-android#203]
Galaxy ZFold 5
App Version 190

Launching the app works fine when I use the narrow, closed outer screen.  However, if my phone is opened to the larger screen, launching the app crashes, with the error message below.

However, if I open with the closed smaller view, then open my phone after the app is already running, the app will adjust successfully and bypasses the crashing error.

This issue might be new, as I don't particularly remember if I had my phone open it closed then, but I suspect I'd have used the large screen, and that issue wasn't occurring.  But, don't quote me on that, as I could be recalling last week's use inaccurately.  Anyway, hope this is helpful! 😁

Thank you for all you do!

![Screenshot_20231106_205747_Grayjay](https://github.com/futo-org/grayjay-android/assets/63543627/cbf69515-f1bb-4cac-afe3-22bfb32c3154)

Version information (version_name = 190, version_code = 190, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = q5q, version-sdk = 33, version-os = samsung/q5quew/q5q:13/TP1A.220624.014/F946U1UEU1AWG5:user/release-keys)

(e, ExceptionActivity, 2023-11-07 01:45:20): Uncaught exception ("Unknown Context"): Index: 1, Size: 0

java.lang.IndexOutOfBoundsException: Index: 1, Size: 0
	at java.util.ArrayList.add(ArrayList.java:483)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.updateMoreButtons(MenuBottomBarFragment.kt:228)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.updateAllButtonVisibility(MenuBottomBarFragment.kt:259)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.updateButtonDefinitions(MenuBottomBarFragment.kt:306)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment$MenuBottomBarView.<init>(MenuBottomBarFragment.kt:103)
	at com.futo.platformplayer.fragment.mainactivity.bottombar.MenuBottomBarFragment.onCreateView(MenuBottomBarFragment.kt:42)
	at androidx.fragment.app.Fragment.performCreateView(Fragment.java:3104)
	at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:524)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
	at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
	at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1433)
	at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2977)
	at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2895)
	at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
	at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:351)
	at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1543)
	at android.app.Activity.performStart(Activity.java:8692)
	at android.app.ActivityThread.handleStartActivity(ActivityThread.java:4219)
	at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
	at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8805)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by koen-futo** [comment]
Should be fixed starting from build 191, hoping to release today.
