### ISSUE TITLE
Crashes on Amazon Fire Tab 10

### ISSUE THREAD

**Issue by bdmihai** [futo-org/grayjay-android#218]
The app crashes on Amazon Fire Tab 10 (install from Google Play Store).

**Comment by koen-futo** [comment]
Can you attach a crash log? We don't have an Amazon Fire Tab 10.

**Comment by bdmihai** [comment]
```
Version information (version_name = 181, version_code = 181, flavor = playstore, build_type = release)
Device information (brand= Amazon, manufacturer = Amazon, device = trona, version-sdk = 28, version-os = PPR1.180610.009)

(e, ExceptionActivity, 2023-11-10 19:20:32): Uncaught exception ("Unknown Context"): Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2f81884 u0 com.futo.platformplayer.playstore/com.futo.platformplayer.services.MediaPlaybackService}

android.app.RemoteServiceException: Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{2f81884 u0 com.futo.platformplayer.playstore/com.futo.platformplayer.services.MediaPlaybackService}
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:211)
	at android.app.ActivityThread.main(ActivityThread.java:6769)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
