### ISSUE TITLE
App Crashes when opening the Creator Tab

### ISSUE THREAD

**Issue by Caotenhoch2** [futo-org/grayjay-android#219]
Language: German
Device Informations are included in the Error Message
Error Messags:
`Version information (version_name = 190, version_code = 190, flavor = stable, build_type = release)
Device information (brand= Redmi, manufacturer = Xiaomi, device = rain, version-sdk = 33, version-os = Redmi/rain_eea/rain:13/TKQ1.221114.001/V14.0.2.0.TGEEUXM:user/release-keys)

(e, ExceptionActivity, 2023-11-07 20:27:26): Uncaught exception ("Unbekannter Kontext"): length=2; index=3

java.lang.ArrayIndexOutOfBoundsException: length=2; index=3
at java.util.Arrays$ArrayList.get(Arrays.java:4210)
at android.widget.ArrayAdapter.getItem(ArrayAdapter.java:394)
at android.widget.ArrayAdapter.createViewFromResource(ArrayAdapter.java:450)
at android.widget.ArrayAdapter.getView(ArrayAdapter.java:416)
at android.widget.Spinner.makeView(Spinner.java:724)
at android.widget.Spinner.layout(Spinner.java:672)
at android.widget.Spinner.onLayout(Spinner.java:634)
at android.view.View.layout(View.java:23967)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1872)
at android.widget.LinearLayout.layoutHorizontal(LinearLayout.java:1856)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1593)
at android.view.View.layout(View.java:23967)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at androidx.appcompat.widget.Toolbar.layoutChildLeft(Toolbar.java:2207)
at androidx.appcompat.widget.Toolbar.onLayout(Toolbar.java:2146)
at android.view.View.layout(View.java:23967)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1872)
at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1694)
at android.widget.LinearLayout.onLayout(LinearLayout.java:1591)
at com.google.android.material.appbar.AppBarLayout.onLayout(AppBarLayout.java:553)
at android.view.View.layout(View.java:23967)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
at com.google.android.material.appbar.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:66)
at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1768)
at com.google.android.material.appbar.AppBarLayout$Behavior.onLayoutChild(AppBarLayout.java:1427)
at com.google.android.material.appbar.AppBarLayout$BaseBehavior.onLayoutChild(AppBarLayout.java:1446)
at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
at android.view.View.layout(View.java:23967)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at android.widget.FrameLayout.layoutChildren(FrameLayout.java:353)
at android.widget.FrameLayout.onLayout(FrameLayout.java:279)
at android.view.View.layout(View.java:23967)
at android.view.ViewGroup.layout(ViewGroup.java:6505)
at androidx.constraintlayout.motion.widget.MotionPaths.setView(MotionPaths.java:640)
at androidx.constraintlayout.motion.widget.MotionController.interpolate(MotionController.java:1286)
at androidx.constraintlayout.motion.widget.MotionLayout.evaluateLayout(MotionLayout.java:3572)
at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:2960)
at android.view.View.measure(View.java:26710)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
at android.view.View.measure(View.java:26710)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1556)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:846)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:725)
at android.view.View.measure(View.java:26710)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
at android.view.View.measure(View.java:26710)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1556)
at android.widget.LinearLayout.measureVertical(LinearLayout.java:846)
at android.widget.LinearLayout.onMeasure(LinearLayout.java:725)
at android.view.View.measure(View.java:26710)
at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
at android.widget.FrameLayout.onMeasure(FrameLayout.java:198)
at com.android.internal.policy.DecorView.onMeasure(DecorView.java:835)
at android.view.View.measure(View.java:26710)
at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4241)
at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2903)
at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3198)
at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2610)
at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9619)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1491)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1499)
at android.view.Choreographer.doCallbacks(Choreographer.java:1114)
at android.view.Choreographer.doFrame(Choreographer.java:1031)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1467)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:211)
at android.os.Looper.loop(Looper.java:300)
at android.app.ActivityThread.main(ActivityThread.java:8410)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)`

**Comment by Caotenhoch2** [comment]
Just saw, that it is a duplicate of #199
