### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by Locorock** [futo-org/grayjay-android#362]
since update 199 the app crashes every time i try to refresh the feed, watch a patreon video and/or open a patreon channel.
here's the log

```
Version information (version_name = 199, version_code = 199, flavor = stable, build_type = release)
Device information (brand= OnePlus, manufacturer = OnePlus, device = OP515BL1, version-sdk = 33, version-os = OnePlus/DN2103EEA/OP515BL1:13/TP1A.220905.001/R.d52fbe-df:user/release-keys)

(e, ExceptionActivity, 2023-11-22 20:31:34): Uncaught exception ("Unknown Context"): findViewById(R.id.time_bar) must not be null

java.lang.NullPointerException: findViewById(R.id.time_bar) must not be null
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewVideoView.<init>(PreviewVideoView.kt:126)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewVideoView.<init>(PreviewVideoView.kt:86)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewNestedVideoView.<init>(PreviewNestedVideoView.kt:38)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewNestedVideoViewHolder.<init>(PreviewNestedVideoViewHolder.kt:27)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewContentListAdapter.createNestedViewHolder(PreviewContentListAdapter.kt:90)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewContentListAdapter.createChild(PreviewContentListAdapter.kt:80)
	at com.futo.platformplayer.views.adapters.feedtypes.PreviewContentListAdapter.createChild(PreviewContentListAdapter.kt:25)
	at com.futo.platformplayer.views.adapters.InsertedViewAdapter.onCreateViewHolder(InsertedViewAdapter.kt:38)
	at com.futo.platformplayer.views.adapters.InsertedViewAdapter.onCreateViewHolder(InsertedViewAdapter.kt:8)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7719)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6804)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6688)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6684)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2362)
	at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1662)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1622)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:687)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4604)
	at androidx.recyclerview.widget.RecyclerView.onMeasure(RecyclerView.java:3981)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26653)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onMeasure(SwipeRefreshLayout.java:705)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:760)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:100)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:2376)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:831)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureHorizontal(LinearLayout.java:1204)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:723)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26653)
	at androidx.constraintlayout.widget.ConstraintLayout$Measurer.measure(ConstraintLayout.java:811)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:632)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:452)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solveVerticalMatchConstraint(Direct.java:750)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:551)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.verticalSolvingPass(Direct.java:486)
	at androidx.constraintlayout.core.widgets.analyzer.Direct.solvingPass(Direct.java:224)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.layout(ConstraintWidgetContainer.java:693)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solveLinearSystem(BasicMeasure.java:160)
	at androidx.constraintlayout.core.widgets.analyzer.BasicMeasure.solverMeasure(BasicMeasure.java:291)
	at androidx.constraintlayout.core.widgets.ConstraintWidgetContainer.measure(ConstraintWidgetContainer.java:120)
	at androidx.constraintlayout.widget.ConstraintLayout.resolveSystem(ConstraintLayout.java:1594)
	at androidx.constraintlayout.widget.ConstraintLayout.onMeasure(ConstraintLayout.java:1708)
	at androidx.constraintlayout.motion.widget.MotionLayout.onMeasure(MotionLayout.java:2936)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at androidx.appcompat.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:145)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1552)
	at android.widget.LinearLayout.measureVertical(LinearLayout.java:842)
	at android.widget.LinearLayout.onMeasure(LinearLayout.java:721)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:7079)
	at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
	at com.android.internal.policy.DecorView.onMeasure(DecorView.java:829)
	at android.view.View.measure(View.java:26653)
	at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:4071)
	at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:2733)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3020)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2442)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9399)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1388)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1396)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1033)
	at android.view.ChoreographerExtImpl.checkScrollOptSceneEnable(ChoreographerExtImpl.java:420)
	at android.view.Choreographer.doFrame(Choreographer.java:900)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1371)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:240)
	at android.os.Looper.loop(Looper.java:351)
	at android.app.ActivityThread.main(ActivityThread.java:8377)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
```

**Comment by koen-futo** [comment]
Thank you for the report. Rolling out a fix now.
