### ISSUE TITLE
Uncaught exception ("Unknown Context"): The Path must start at (0,0) and end at (1,1)

### ISSUE THREAD

**Issue by Bluscream** [futo-org/grayjay-android#363]
```
Version information (version_name = 199, version_code = 199, flavor = stable, build_type = release)
Device information (brand= oculus, manufacturer = Oculus, device = eureka, version-sdk = 32, version-os = )

(e, ExceptionActivity, 2023-11-22 19:41:47): Uncaught exception ("Unknown Context"): The Path must start at (0,0) and end at (1,1)

java.lang.IllegalArgumentException: The Path must start at (0,0) and end at (1,1)
 at android.view.animation.PathInterpolator.initPath(PathInterpolator.java:168)
 at android.view.animation.PathInterpolator.initCubic(PathInterpolator.java:158)
 at android.view.animation.PathInterpolator.parseInterpolatorFromTypeArray(PathInterpolator.java:142)
 at android.view.animation.PathInterpolator.<init>(PathInterpolator.java:104)
 at android.view.animation.AnimationUtils.createInterpolatorFromXml(AnimationUtils.java:429)
 at android.view.animation.AnimationUtils.loadInterpolator(AnimationUtils.java:342)
 at com.android.internal.policy.DecorView.<init>(DecorView.java:303)
 at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2375)
 at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2717)
 at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:451)
 at com.android.internal.app.AlertController.installContent(AlertController.java:269)
 at android.app.AlertDialog.onCreate(AlertDialog.java:439)
 at android.app.Dialog.dispatchOnCreate(Dialog.java:432)
 at android.app.Dialog.show(Dialog.java:321)
 at com.futo.platformplayer.UIDialogs$Companion.showDialog(UIDialogs.kt:192)
 at com.futo.platformplayer.UIDialogs$Companion.showConfirmationDialog(UIDialogs.kt:238)
 at com.futo.platformplayer.states.StateApp$handleCaptchaException$1.invokeSuspend(StateApp.kt:720)
 at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
 at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
 at android.os.Handler.handleCallback(Handler.java:938)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:214)
 at android.os.Looper.loop(Looper.java:304)
 at android.app.ActivityThread.main(ActivityThread.java:7905)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010)
 Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@2e809cc, Dispatchers.Main]
 ```

**Comment by Zvonimir-FUTO** [comment]
This seems to be fixed in latest version (264) of Grayjay. Feel free to open a new issue if you are still encountering this.
