### ISSUE TITLE
Update broke app 

### ISSUE THREAD

**Issue by barkerd427** [futo-org/grayjay-android#470]
I keep getting this error when I try to download something, and I lost all my downloads.

Version information (version_name = 209, version_code = 209, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = cheetah, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2023-12-10 03:21:16): Uncaught exception ("Unknown Context"): Starting FGS without a type  callerApp=ProcessRecord{397e639 31561:com.futo.platformplayer/u0a570} targetSDK=34

android.app.MissingForegroundServiceTypeException: Starting FGS without a type  callerApp=ProcessRecord{397e639 31561:com.futo.platformplayer/u0a570} targetSDK=34
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:53)
	at android.app.MissingForegroundServiceTypeException$1.createFromParcel(MissingForegroundServiceTypeException.java:49)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4870)
	at android.os.Parcel.readParcelable(Parcel.java:4852)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3052)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.os.Parcel.readException(Parcel.java:2966)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6761)
	at android.app.Service.startForeground(Service.java:775)
	at com.futo.platformplayer.services.DownloadService.notifyDownload(DownloadService.kt:253)
	at com.futo.platformplayer.services.DownloadService.onStartCommand(DownloadService.kt:60)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4821)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8177)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)

**Comment by koen-futo** [comment]
Fixing now.

**Comment by koen-futo** [comment]
Deploying now.

**Comment by koen-futo** [comment]
For affected users, do not delete the app. Just go to the https://grayjay.app website and redownload and install the APK. You user data should be unaffected.
