### ISSUE TITLE
IndexOutOfBoundsException upon removing multiple videos from ongoing Queue View Activity

### ISSUE THREAD

**Issue by ShareASmile** [futo-org/grayjay-android#638]
Steps to reproduce:
1. Add to Queue at least 4-5 videos, make sure Queue is playing on the player.
2. Open Queue view present below the player, tap last or last but one video in the list to play 

..OR rearrange Now Playing Video to last but one position in the list. Now try to remove more than one videos in the Queue before that & last one including now playing. it may induce IndexOutOfBoundsException exception

3.  OR.. instead of Step 2, Press next button (on the player) as many times as needed to go to last video in the list, Make sure queue is playing its last video. Now open Queue view, Try to remove mutiple previous videos from the Queue & it induces following IndexOutOfBoundsException exception :-

Version info = 221, 225,
version_code = 221, 225,
flavor = stable,
build_type = release)
Device information samsung a22x,
version-sdk = 33,
version-os = samsung one ui 5.0

Crash Report:

(e, ExceptionActivity, 2024-01-07 17:02:27): Uncaught exception ("Unknown Context"): Index: 3, Size: 3

java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
	at java.util.ArrayList.get(ArrayList.java:437)
	at com.futo.platformplayer.states.StatePlayer.getPrevQueueItem(StatePlayer.kt:424)
	at com.futo.platformplayer.views.video.FutoVideoPlayer.updateNextPrevious(FutoVideoPlayer.kt:409)
	at com.futo.platformplayer.views.video.FutoVideoPlayer$26$1.invokeSuspend(FutoVideoPlayer.kt:392)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@35c8eb6, Dispatchers.Main]

**Comment by ShareASmile** [comment]
Ok, i would keep it open then, untill a fix arrives, Thanks.

**Comment by ShareASmile** [comment]
Closing as fixed with commit :-
https://github.com/futo-org/grayjay-android/commit/196cacb452b2decf50bf0e80a2e2079b34ced37f
