### ISSUE TITLE
Crash after opening the app

### ISSUE THREAD

**Issue by birdup000** [futo-org/grayjay-android#706]
Version information (version_name = 227, version_code = 227, flavor = stable, build_type = release)
Device information (brand= samsung, manufacturer = samsung, device = beyond2q, version-sdk = 31, version-os = )

(e, ExceptionActivity, 2024-01-18 05:10:39): Uncaught exception ("Unknown Context"): Runtime is already closed

com.caoccao.javet.exceptions.JavetException: Runtime is already closed
	at com.caoccao.javet.values.reference.V8ValueReference.close(V8ValueReference.java:64)
	at com.caoccao.javet.interop.V8Runtime.removeReferences(V8Runtime.java:2988)
	at com.caoccao.javet.interop.V8Runtime.removeAllReferences(V8Runtime.java:2872)
	at com.caoccao.javet.interop.V8Runtime.close(V8Runtime.java:540)
	at com.caoccao.javet.interop.V8Runtime.close(V8Runtime.java:528)
	at com.futo.platformplayer.engine.V8Plugin$stop$1.invoke(V8Plugin.kt:177)
	at com.futo.platformplayer.engine.V8Plugin$stop$1.invoke(V8Plugin.kt:171)
	at com.futo.platformplayer.engine.V8Plugin.whenNotBusy(V8Plugin.kt:223)
	at com.futo.platformplayer.engine.V8Plugin.stop(V8Plugin.kt:171)
	at com.futo.platformplayer.api.media.platforms.js.JSClient.disable(JSClient.kt:256)
	at com.futo.platformplayer.api.media.PlatformClientPool$1.invoke(PlatformClientPool.kt:34)
	at com.futo.platformplayer.api.media.PlatformClientPool$1.invoke(PlatformClientPool.kt:28)
	at com.futo.platformplayer.constructs.Event1.emit(Event.kt:99)
	at com.futo.platformplayer.engine.V8Plugin$stop$1.invoke(V8Plugin.kt:181)
	at com.futo.platformplayer.engine.V8Plugin$stop$1.invoke(V8Plugin.kt:171)
	at com.futo.platformplayer.engine.V8Plugin.whenNotBusy(V8Plugin.kt:223)
	at com.futo.platformplayer.engine.V8Plugin.stop(V8Plugin.kt:171)
	at com.futo.platformplayer.api.media.platforms.js.JSClient.disable(JSClient.kt:256)
	at com.futo.platformplayer.states.StatePlatform$updateAvailableClients$2.invokeSuspend(StatePlatform.kt:174)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by Kelvin-FUTO** [comment]
Thats weird, it appears to be disabling a client on startup. As if one was already active.
Does this happen every startup?
Any idea what plugins were enabled?

**Comment by Kelvin-FUTO** [comment]
In upcoming v233 I added a few catches that should theoretically prevent this from happening.

We also added updating from the crash activity, so that you don't have to reinstall it manually.
Hopefully this resolves the issue, but keep me posted (reopen this issue).
