### ISSUE TITLE
OOM when downloading large playlist

### ISSUE THREAD

**Issue by effleurager** [futo-org/grayjay-android#847]
When viewing the Downloads fragment after starting a large (> 200 videos) playlist download, the app will try to allocate memory for each video (presumably list objects) before failing ungracefully.

```
Version information (version_name = 235, version_code = 235, flavor = stable, build_type = release)
Device information (brand= google, manufacturer = Google, device = husky, version-sdk = 34, version-os = )

(e, ExceptionActivity, 2024-03-07 14:48:37): Uncaught exception ("Unknown Context"): Failed to allocate a 32 byte allocation with 80608 free bytes and 78KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.

java.lang.OutOfMemoryError: Failed to allocate a 32 byte allocation with 80608 free bytes and 78KB until OOM, target footprint 536870912, growth limit 536870912; giving up on allocation because <1% of heap free after GC.
	at java.util.ArrayList.iterator(ArrayList.java:954)
	at okhttp3.internal.concurrent.TaskRunner.awaitTaskToRun(TaskRunner.kt:167)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:59)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by Kelvin-FUTO** [comment]
Active downloads are currently not paged, which does cause this issue for some phones (due to video thumbnails on ui).

To verify, this is only when you're *viewing* the downloads fragment while its downloading correct?

**Comment by effleurager** [comment]
That's correct

**Comment by Kelvin-FUTO** [comment]
This should be solved in upcoming update 237+
